<a href="https://colab.research.google.com/github/JayasriPalanisamy/DS_Sujatha/blob/main/DS_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])

In [ ]:
a

array([1, 2, 3])

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print

<function print>

In [ ]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

(3, 3)

In [ ]:
matrix.size

9

In [ ]:
matrix.dtype

dtype('int64')

In [ ]:
matrix.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.max(matrix)

9

In [ ]:
np.min(matrix)

1

In [ ]:
np.max(matrix,axis=0)

array([7, 8, 9])

In [ ]:
np.min(matrix, axis=0)

array([1, 2, 3])

In [ ]:
np.max(matrix,axis=1)

array([3, 6, 9])

In [ ]:
np.min(matrix, axis=1)

array([1, 4, 7])

In [ ]:
np.mean(matrix)

5.0

In [ ]:
np.var(matrix)

6.666666666666667

In [ ]:
np.std(matrix)

2.581988897471611

In [ ]:
np.sqrt(matrix)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

## Pandas

In [ ]:
import pandas as pd

In [ ]:
pd.Series()

<ipython-input-32-fa15c544da3b>:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  pd.Series()


Series([], dtype: float64)

In [ ]:
lst = ["Henry", 'John', 'Manu']
# Create dataframe
firstdf = pd.DataFrame(lst)
# the df
firstdf

0
0  Henry
1   John
2   Manu

In [ ]:
firstdf.index(['a','b','c'])

TypeError: ignored

In [ ]:
firstdf = pd.DataFrame(lst, index=['a','b','c'], columns=['Names'])
firstdf

Names
a  Henry
b   John
c   Manu

In [ ]:
seconddf = pd.DataFrame(matrix)
seconddf

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
# Dataframe from multi-dimensional list
mltlist = [[1, 'abc'], [2, 'def'], [3, 'tyu']]
thirddf = pd.DataFrame(mltlist, index=[1,2,3], columns=['SNo', 'Names'])
thirddf

SNo Names
1    1   abc
2    2   def
3    3   tyu

In [ ]:
# Dataframe from a dictionary
no = [1,2,3]
names = ['Manu', 'Sonu', 'Tina']
age = [5, 10, 15]
dfdict = {'No':no, 'Names':names, 'Age':age}
childdf = pd.DataFrame(dfdict)
childdf

No Names  Age
0   1  Manu    5
1   2  Sonu   10
2   3  Tina   15

In [ ]:
# Slicing and dicing the df
# Select two colums
childdf[['No', 'Age']]

No  Age
0   1    5
1   2   10
2   3   15

In [ ]:
childdf['Age']

0     5
1    10
2    15
Name: Age, dtype: int64

In [ ]:
# Select columns using index
childdf[childdf.columns[1:]]

Names  Age
0  Manu    5
1  Sonu   10
2  Tina   15

In [ ]:
childdf.columns[1:]

Index(['Names', 'Age'], dtype='object')

In [ ]:
# .loc[] -> takes only index labels
childdf.loc[1:, 'Names':]

Names  Age
1  Sonu   10
2  Tina   15

In [ ]:
childdf.loc[1:, ]

No Names  Age
1   2  Sonu   10
2   3  Tina   15

In [ ]:
childdf.loc[1, ]

No          2
Names    Sonu
Age        10
Name: 1, dtype: object

In [ ]:
# .iloc[] -> integer index based
childdf.iloc[:, 1:]

Names  Age
0  Manu    5
1  Sonu   10
2  Tina   15

In [ ]:
# Inserting a column
# Create a list for the column
height = [123,136,156]
childdf['Height'] = height
childdf

No Names  Age  Height
0   1  Manu    5     123
1   2  Sonu   10     136
2   3  Tina   15     156

In [ ]:
# Inserting a column using assign()
childdf = childdf.assign(Place = ['chennai', 'cbe', 'trichy'])
childdf

No Names  Age  Height    Place
0   1  Manu    5     123  chennai
1   2  Sonu   10     136      cbe
2   3  Tina   15     156   trichy

In [ ]:
# Adding columns using insert()
# Position on where to be inserted can be added
